name: Create pdf

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  create-pdf:
    runs-on: ubuntu-latest
    container:
      image: browserless/chrome
      options: --user root
    steps:
      - name: Wait
        run: sleep 10
      - name: html to pdf
        run: |
          /usr/bin/google-chrome \
            --no-sandbox \
            --headless \
            --disable-gpu \
            --print-to-pdf=./menu.pdf \
            https://ddsnackshack.github.io/menu/
      - uses: actions/upload-artifact@v3
        with:
          name: menu
          path: ./menu.pdf
