name: Create pdf

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

jobs:
  pdf:
    runs-on: ubuntu-latest
    steps:
#      - name: Wait
#        run: sleep 10
      - name: html to pdf
        uses: misaelnieto/web_to_pdf_action@master
        with:
          webPageURL: https://ddsnackshack.github.io/menu/
          outputFile: ./menu.pdf
          usePuppeteer: true
          useScreen: false
          #pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
      - uses: actions/upload-artifact@v3
        with:
          name: menu
          path: ./menu.pdf
